### PR TITLE
feat: add local upload and local save

### PR DESCRIPTION
**Pull request by akitaSummer**
- [x] refactor sidebar
- [x] local upload
- [x] local save

### CODE REVIEW

**Comment by AGDholo** [comment]
Online preview:
https://hedgehog-lab-git-feature-aktia.sniper.vercel.app/

**Comment by AGDholo** [comment]
Thank you very much for your contribution.

There are several problems:

- [ ] Do not use low-contrast colors for buttons, and preferably do not use gradient colors, which hinder the adaptation of a11y and dark mode.

- [ ] The logo that appears after the sidebar is folded away, rather than a hint to the right of a button or tutorial, can confuse users.

- [ ] On low-resolution devices or mobile devices, the function cannot be used normally, the tutorial button disappears, and the result box disappears.

**Comment by akitaSummer** [comment]
@AGDholo I have fixed the bug，please review.

**Comment by AGDholo** [comment]
The latest commit has been deployed to preview:
https://hedgehog-lab-3lh136vfs.vercel.app/

**Comment by AGDholo** [comment]
Thank you very much for your contribution. As it involves functional changes, the PR may need to wait for review and merge.

**Comment by AGDholo** [comment]
Merged, Thanks @akitaSummer .

**Pull request merged**
