### PR TITLE
Refactor: First step to split front-end and computing logic

### PR DESCRIPTION
**Pull request by imtsuki**
This PR mainly addressed the following problems:

- Current implementation somehow mixed the front-end code and
the actual computing logic. This PR moved all the "back-end"
into `core` folder. However, in the future, we should expect those
codes to sit in a separate package, like `hedgehog-core`.
- Code cleanup. This PR removed most of the redundant code and
dependencies and did a whole-project formating. In the future, we
should use ESlint to force this workflow. Extra PR would be
pleased.

There are some future discussions:

- Move to Yarn. NPM sucks at workspace management, which blocks
the complete separation of `hedgehog-core`. Yarn is also the
recommended package manager of React.
- It is unusual to add type annotations in JS files nowadays,
and we see both `flow` and `typescript` are presented in deps.
We should either switch to TypeScript internally, or remove the
current type annotations in JS sources.

Signed-off-by: imtsuki <me@qjx.app>

### CODE REVIEW

**Comment by imtsuki** [comment]
Related: #18

**Comment by lidangzzz** [comment]
我好慌，一下子改了这么多，不知道该不该approve = =

@AGDholo 你觉得呢？

**Comment by AGDholo** [comment]
@lidangzzz 这老哥挺厉害的，把耦合的代码全部拆分了，拆的真的很不错，跑着没问题我觉得就能合并。
在我看来这个提交很厉害也很关键，完全解耦，让后续的贡献和项目管理的效率大大增加。

其他讨论：
1. 为什么用 monaco-editor 而不是用 react-monaco-editor？
2. 关于包管理的问题，我个人项目也一直在用 yarn，但是我看之前其他人的大部分提交都是走的 npm，因为没人用，所以我就把 yarn 删了，这个可以讨论下，我个人也比较推荐 yarn。
3. 确实应该完全应用 ts 文件，不过我对 ts 不熟悉，这一块得让社区来做。

**Comment by lidangzzz** [comment]
@AGDholo @imtsuki 好的，我给merge进去了。谢谢大佬们，给大佬点烟，666

**Pull request merged**
